### PR TITLE
Decimal places for analog sensor

### PR DESCRIPTION
**Pull request by vauriga**
In Loxone analog values can have 3 digits

### CODE REVIEW

**Comment by JoDehli** [comment]
@vauriga I think a better solution is to use the format from loxone because not everyone wants 3 digits. Please try the dev branch and let me know what you think about this solution? Does it work for you?

**Comment by vauriga** [comment]
@JoDehli sure it is, I will check it later. great work on this integration, thanks

**Comment by vauriga** [comment]
@JoDehli display format works perfectly, so closing this

**Comment by JoDehli** [comment]
@vauriga I had to change the format again because other users had problems after the last change. Can you try the dev branch if it still works for you? I hope so ;-)

**Pull request closed without merging**
