### PR TITLE
Add support for button class

### PR DESCRIPTION
**Pull request by gigatexel**
This PR fixes https://github.com/JoDehli/PyLoxone/issues/281

Previously, Loxone VI's configured as a Pushbutton were represented as a switch.
This PR replaces them with Buttons so they are stateless and more conforming the situation in Loxone config.

### CODE REVIEW

**Comment by JoDehli** [comment]
@gigatexel Thanks for your help. But if you make a pull request can you please first make sure that you are merge my latest version into your branch. This would make it much easier.

**Comment by JoDehli** [comment]
@gigatexel can you first merge the latest version into your branch. I changed the token storing.

**Comment by gigatexel** [comment]
> @gigatexel can you first merge the latest version into your branch. I changed the token storing.

Hi, I already did that.
See https://github.com/gigatexel/PyLoxone/tree/master/custom_components/loxone

**Comment by JoDehli** [comment]
@gigatexel but not in the pull request. There is also the __init__.py file changed.

**Pull request closed without merging**
