### PR TITLE
Added all scene depended changes from #350

### PR DESCRIPTION
**Pull request by JoDehli**
Climate changes from #350

### CODE REVIEW

**Comment by JoDehli** [comment]
@gigatexel Here I think we need to make sure that all lights are loaded before we can generate the scenes. Have you checked that? 

In the past I had problems with large installations. That is why the scenes are handled differently then other platforms.

**Comment by JoDehli** [comment]
@gigatexel And if that works I think it is hopefully ok to add scenes by default. On larger installations there are hundreds of scenes generated on start. So hopefully we get not a lot of issues back.

But when it is working the config settings should also be removed from the gui and from the settings.

**Comment by gigatexel** [comment]
Thanks for you feedback on the history of why things are implemented as they are 👍 

I just did a test by adding 40 light controllers v2 with each 15 scenes defined. This renders 600 scenes and processes well.
Todo:

- see what I can do to make sure lights are loaded first
- check again if I can make reloading the integration more clean. Reloading causes a connection error in the logs that corrects itself (polls on a connection that was gracefully disconnected).

Do you want me do create a specific PR for this then?

**Comment by JoDehli** [comment]
@gigatexel I think the best way to test is to make a sleep in the different integration setup methods. 

I think a problem is when the lights are not loaded before the scene loads. This could be not only when the system has a lot of lights it can be a problem when other integrations take a lot of time to setup. When we get issues I think we can go back an call the scene setup at the same point as we do it now. 

I can remove the option from the configuration panel and look that the old values in the settings we removed on migration. 

After merging this pr we can go to the next improvement.

**Comment by gigatexel** [comment]
Are we sure that this race condition can still be an issue?
If I look at the scenes implementation, it seems that it just parses the `LightControllerV2` blocks and then generates scenes from it. There seems no link to the actual `LightControllerV2` device?
I will test tomorrow if scenes still generate and work when no `light` entities are loaded.

**Comment by JoDehli** [comment]
@gigatexel please no code from chat gpt! 

There is no such function in home assistant.

**Comment by JoDehli** [comment]
@gigatexel  hass.async_when_setup does not exist. from homeassistant.setup import async_when_setup does exist.

**Comment by JoDehli** [comment]
@gigatexel what do you think could this implementation with a dispatcher work?

**Comment by JoDehli** [comment]
@gigatexel of course the print messages must be removed. ;-)

**Comment by gigatexel** [comment]
> @gigatexel of course the print messages must be removed. ;-)

I will test tomorrow on a VM.

**Comment by JoDehli** [comment]
@gigatexel I removed the options for the scene generation. Migration tested only for version 3 to 4. Hope it works for the older versions as well.

**Comment by JoDehli** [comment]
@gigatexel I think the reload is not necessary for now. I already made a complete rewrite and it does use a different websoclet lib.  I hope I can make the reload working on the new implementation. 

I already tried it but never got it really to work.

**Comment by gigatexel** [comment]
> @gigatexel what do you think could this implementation with a dispatcher work?

isn't there an `unsub()` missing after the scenes get generated?

**Comment by JoDehli** [comment]
@gigatexel I do not know. That is why I asked. :-)

**Comment by gigatexel** [comment]
The edits above let the code run, but scenes are not generated.
I got the exact same issue when I was trying to let the integration reload. Something in the comms is causing the MS not to send an event containing the moodList. Moodlist is never recieved.

**Comment by JoDehli** [comment]
@gigatexel  I do not use any scenes that is why I was bit sure if it works. Does it work with the current stable release.

**Comment by gigatexel** [comment]
> @gigatexel I do not use any scenes that is why I was bit sure if it works. Does it work with the current stable release.

I suspect there is some kind of race condition in the api that causes the moodList not to be picked up.
I looked into it with WireShark and the moodList is in fact sent from MS to HA.

image

**Comment by JoDehli** [comment]
@gigatexel I checked all text messages are not parsed anymore. I do not know if it is a problem which was introduced from Pyloxone update or loxone update.

**Comment by JoDehli** [comment]
@gigatexel I leave the scene generation as it is in the current implementation. I spent a few hours with this problem and I have not time for this improvement as it works stable now.

**Comment by gigatexel** [comment]
No problem. I will continue my search next week to find what bug might be in the api.

**Comment by JoDehli** [comment]
@gigatexel there is no bug in the api. The moods list will only be sent after the the connection is established. It is not part of the config json. That is why we must wait a view seconds before searching for the moods. If we only wait for the light to be setup it is to early and the moods list is still empty and no scenes can be generated. Of course it can be implemented so that the lights generate the scenes when the receive the moods but to be honest the home assistant architecture is getting more and more difficult and more and more a nightmare that my motivation concentrates to keep the component running.

**Pull request closed without merging**
