### PR TITLE
Support VTI's

### PR DESCRIPTION
**Pull request by gigatexel**
See readme.

### CODE REVIEW

**Comment by JoDehli** [comment]
@gigatexel  you should refer to a asset from your branch. If you really want to include the image place it in the root folder. If you want you can delete the other image which is not used anymore. I think it is called cloud config.

**Comment by gigatexel** [comment]
> @gigatexel you should refer to a asset from your branch. If you really want to include the image place it in the root folder. If you want you can delete the other image which is not used anymore. I think it is called cloud config.

Thanks for the suggestion. Should be fixed now.

**Comment by JoDehli** [comment]
merged manually

**Comment by gigatexel** [comment]
> merged manually

is ther esomething I'm doing wrong that causes the need to merge manually?

**Comment by JoDehli** [comment]
@gigatexel no. Maybe I is because I am not a really expert in git and pull request. I do it normally like this I compare it what is different and change the things what I prefer on the fly. I could also push it first back to the pull request and then merge it but I was in a hurry yesterday because I have 3 other projects which I must work on. 

And at the moment I have 2 main problems on which I work on this project. There is not much time for improvements an new features.

**Comment by gigatexel** [comment]
> @gigatexel no. Maybe I is because I am not a real expert in git and pull request. I do it normally like this I compare it what is different and change the things what I prefer on the fly. I could also push it first back to the pull request and then merge it but I was in a hurry yesterday because I have 3 other projects which I must work on.
> 
> And at the moment I have 2 main problems on which I work on this project. There is not much time for improvements an new features.

I'm also not a github wizard, that's why I was asking :-)

What main problems do you have with pyLoxone? Maybe I can help/assist?

**Pull request closed without merging**
