### PR TITLE
Add Shade and sun automation capability to covers + fixes

### PR DESCRIPTION
**Pull request by lukaskroczek**

### CODE REVIEW

**Comment by lukaskroczek** [comment]
Hi @JoDehli,

I added the capability to enable/disable sun automation and quick shade.

Also, I found missing device_class GATE for LoxoneGate (see spec: 
animation
○ 0 = Garage Door
○ 1 = Single Gate opening to the left
○ 2 = Single Gate opening to the right
○ 3 = Gate opening to both sides
○ 4 = Folding door opening to the left
○ 5 = Folding door opening to the right
)

**Comment by shvnrg** [comment]
Could this change result in problems with scenes. Since some days i have problems executing scenes with covers involved.
If the  scene is integrated in an automation this leads to an error and aborts the automation

Error [547590411712] Entity cover.fenster_kuche_arbeitsflache does not support this service.

To reproduce just add a Cover Entity or Device in a scene. Complete log attached
[errorlog home assistant pyloxone.txt](https://github.com/JoDehli/PyLoxone/files/13327562/errorlog.home.assistant.pyloxone.txt)

**Comment by JoDehli** [comment]
@shvnrg you can try the service manually. If the service is not present anymore you can either remove it from your automation or give the cover a different animation. 

Is it a shade command which you send?

**Comment by shvnrg** [comment]
I dont use the service directly. I am working over the scenes configuration.
Added a scene, added the entity, configured the height. saved the scene.

When i am using services direct in an automation there are nor errors. I use mainly cover - open, close, set position.

Tried to delete the "old" scene and recreate it, same problem. In the Scene itself i have no options for configuration.

**Comment by shvnrg** [comment]
Just did a quick check of the scenes.yaml. Looks like the Scene saves "current_tilt_position: 0"
Which is probably the problem. After deleteing it looks like there are no errors

**Comment by lukaskroczek** [comment]
Hi @shvnrg, can you please send us your scene? I don't know what you set up and would need this to reproduce the issue. And please add how it is set up in Loxone.

**Comment by shvnrg** [comment]
I will try to give you a complete rundown, thats probably the best way to not miss anything
Sorry, will be long ....


**Loxone Config from one of the devices.** 
Did not touch them since installation. My stuff is all managed in Home Assistant, but maybe there is already a misconfiguration.
image

**Creating the Scene**

Home Assistant -> Settings -> Automations & scenes -> Scenes -> Add Scene
image
Dont mind the name of the Device, it is changed in Home Assistant via GUI
Click the Device and change value as needed:
image

->Save Scene

**Testing**
Activating the Scene now changes the cover to the position, but gives this error:
image
If only the scene is activated it will do what you want but throw a error in the log files. If you use the Scene in an automation it will stop the automation because of the error.

**Created Scene in scenes.yaml**
```
- id: '1699808002428'
  name: Test Scene for Tilt Problem
  entities:
    cover.fenster_buro_schreibtisch:
      current_position: 31.200000000000003
      current_tilt_position: 100
      uuid: 17fac420-026d-3d23-ffff112233445566
      device_typ: Jalousie
      platform: loxone
      room: Büro
      category: Beschattung
      current_shade_mode: ' '
      current_position_loxone_style: 69
      automatic_text: Automatik Beschattung wegen geschlossener Jalousie für heute
        inaktiv.
      auto_state: 'off'
      is_sun_automation_enabled: 'off'
      device_class: blind
      friendly_name: Fenster Büro Schreibtisch
      supported_features: 1039
      state: open
  metadata: {}
```

**Workaround**
Deleting the following line is a workaround. Then the scene activates and there are no problems:
`      current_tilt_position: 100`

**Physical Hardware**
I am not sure about the translation here so i thought i show you how the cover looks. It is used in Germany in many homes. Very simple up and down cover for the windows
image

**Comment by lukaskroczek** [comment]
Hi @shvnrg, thank you for the details you provided Based on the info you provided, you use a Jalousie type called "Shutter". I checked the Loxone structure file and PyLoxone code and I found a discrepancy/bug.

@JoDehli : https://github.com/JoDehli/PyLoxone/pull/214 created

Anyway, this afternoon I want to test it and find out if it really solves the @shvnrg's issue. It will be a little complicated as I don't have "Automatic blinds integrated" but only "Automatic blinds". Hopefully, I will be able to reproduce it anyway.

**Comment by shvnrg** [comment]
Just updated to 0.4.10 -> No change in behaviour at the moment.

If you need more infos just ping me.

**Comment by lukaskroczek** [comment]
@shvnrg and @JoDehli : after investigation I found the issue. I prepared a fix in https://github.com/JoDehli/PyLoxone/pull/215.

Hopefully, I was able to reproduce it with "Automatic blinds". 
The property current_cover_tilt_position is propagated to scenes because
an entity has attribute/property current_cover_tilt_position with value even if it is not tiltable cover. 

I add a condition to return value only if it is BLIND and return None in other cases. After that, property current_cover_tilt_position is not propagated to scenes.

@shvnrg : anyway, for already created scenes you need to delete current_cover_tilt_position manually. For new scenes, the current_cover_tilt_position should not be propagated.

One more comment: It looks like only BLIND is a tiltable cover device class. If there is another, then it needs to be added on lines 410 and 475.

**Pull request merged**
