### PR TITLE
Feature/new components

### PR DESCRIPTION
**Pull request by cabeljunky**
I have missed a couple of entries. This lead to add some other items an missing attributes.

This commit contain new things and some code alignment
- Added Ventilation
- Added Presence Detector
- Update binary sensor
- Update all other component to have the same structure and type safety.
- Added the device URL
- Added missing device names
- Update the Sensor to accept device class and icon
- Added the parent ID to match the sensors to an entry
- Added removal option for component

I have removed the overhead of the custom sensor. as the code is manly the same Need only some additional check and not fill in all the info. This can also be done to the rest.

I have removed some of the helper functions as they where only used in the component. And the function was only a wrapper. Better to have it in the component.

### CODE REVIEW

**Comment by JoDehli** [comment]
@cabeljunky Thank you very much for your pull request. I made only one change on the fan to get rid of a error message. 

If you are interested to help more you are welcome. I have such a small installation that I can not really test a lot. And maybe you have seen that I started a complete rewrite of the communication to the loxone. But I am not happy with it. I have some problems and I can not find a solution. But if you want to help I can tell you why I want to rewrite it. 

Thanks again for your help!!!!

**Comment by cabeljunky** [comment]
Hello @JoDehli,

My current setup is a bit more more extensive. 
So that means I can add a bit more components to the module. 

I wanted also to add some of the Air device details like the battery. But need a bit more understanding of your code and the api.

If you can share what your issue is maybe I can help or find a solution for it.

**Comment by JoDehli** [comment]
Very nice that you are interested to improve the integration. If you want you can join the discord channel I have made:

https://discord.gg/vXJ2MZka

**Comment by JoDehli** [comment]
@cabeljunky by the way do you use a gen2 or a gen1.

**Comment by cabeljunky** [comment]
I have now a miniserver go (gen1), but I will order the miniserver compact.

**Comment by JoDehli** [comment]
Very good I think the gen2 and compact has the same software. I want to make it work with the new gen2 but I have no access to it. It is a little change. Maybe you can help me if you have a the new server.

**Pull request merged**
