### PR TITLE
Fix on/off for Lights controller v2

### PR DESCRIPTION
**Pull request by lukaskroczek**
LightControllerv2 has 2 default "effects".

Turn on - id 99
Turn off - id 0

### CODE REVIEW

**Comment by JoDehli** [comment]
@lukaskroczek I hope the on command with the 99 is suited to every user configuration. For my system it is working. But to be sure I couldn't reproduce the error you mentioned.

**Comment by lukaskroczek** [comment]
@JoDehli : in this case (when mood 99 is not found) they turn on in manual mode, where brightness depends on attribute MaxAbr. 

The best way will be to add a check if mood 99 exists. If yes, use changeTo/99 else use plus

**Comment by JoDehli** [comment]
@lukaskroczek now I merged all your changes to the master branch and also my dev branches. I did not test it because I do not use any lights and also no climate controls. I also made a new release. Now we will see if it is ok for all the users. If we have problems I will contact you. Maybe you can help with upcoming problems. 

Thanks again for you help.

**Comment by lukaskroczek** [comment]
@JoDehli : if there will be any issue, feel free to contact me and I will provide fix.

**Pull request merged**
